/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.irrigation.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ParcelData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8122733970287602334L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ParcelData\",\"namespace\":\"org.irrigation.schema\",\"fields\":[{\"name\":\"T\",\"type\":\"int\"},{\"name\":\"H\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ParcelData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ParcelData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ParcelData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ParcelData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ParcelData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ParcelData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ParcelData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ParcelData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ParcelData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int T;
  private int H;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ParcelData() {}

  /**
   * All-args constructor.
   * @param T The new value for T
   * @param H The new value for H
   */
  public ParcelData(java.lang.Integer T, java.lang.Integer H) {
    this.T = T;
    this.H = H;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return T;
    case 1: return H;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: T = (java.lang.Integer)value$; break;
    case 1: H = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'T' field.
   * @return The value of the 'T' field.
   */
  public int getT() {
    return T;
  }


  /**
   * Sets the value of the 'T' field.
   * @param value the value to set.
   */
  public void setT(int value) {
    this.T = value;
  }

  /**
   * Gets the value of the 'H' field.
   * @return The value of the 'H' field.
   */
  public int getH() {
    return H;
  }


  /**
   * Sets the value of the 'H' field.
   * @param value the value to set.
   */
  public void setH(int value) {
    this.H = value;
  }

  /**
   * Creates a new ParcelData RecordBuilder.
   * @return A new ParcelData RecordBuilder
   */
  public static org.irrigation.schema.ParcelData.Builder newBuilder() {
    return new org.irrigation.schema.ParcelData.Builder();
  }

  /**
   * Creates a new ParcelData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ParcelData RecordBuilder
   */
  public static org.irrigation.schema.ParcelData.Builder newBuilder(org.irrigation.schema.ParcelData.Builder other) {
    if (other == null) {
      return new org.irrigation.schema.ParcelData.Builder();
    } else {
      return new org.irrigation.schema.ParcelData.Builder(other);
    }
  }

  /**
   * Creates a new ParcelData RecordBuilder by copying an existing ParcelData instance.
   * @param other The existing instance to copy.
   * @return A new ParcelData RecordBuilder
   */
  public static org.irrigation.schema.ParcelData.Builder newBuilder(org.irrigation.schema.ParcelData other) {
    if (other == null) {
      return new org.irrigation.schema.ParcelData.Builder();
    } else {
      return new org.irrigation.schema.ParcelData.Builder(other);
    }
  }

  /**
   * RecordBuilder for ParcelData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ParcelData>
    implements org.apache.avro.data.RecordBuilder<ParcelData> {

    private int T;
    private int H;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.irrigation.schema.ParcelData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.T)) {
        this.T = data().deepCopy(fields()[0].schema(), other.T);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.H)) {
        this.H = data().deepCopy(fields()[1].schema(), other.H);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ParcelData instance
     * @param other The existing instance to copy.
     */
    private Builder(org.irrigation.schema.ParcelData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.T)) {
        this.T = data().deepCopy(fields()[0].schema(), other.T);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.H)) {
        this.H = data().deepCopy(fields()[1].schema(), other.H);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'T' field.
      * @return The value.
      */
    public int getT() {
      return T;
    }


    /**
      * Sets the value of the 'T' field.
      * @param value The value of 'T'.
      * @return This builder.
      */
    public org.irrigation.schema.ParcelData.Builder setT(int value) {
      validate(fields()[0], value);
      this.T = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'T' field has been set.
      * @return True if the 'T' field has been set, false otherwise.
      */
    public boolean hasT() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'T' field.
      * @return This builder.
      */
    public org.irrigation.schema.ParcelData.Builder clearT() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'H' field.
      * @return The value.
      */
    public int getH() {
      return H;
    }


    /**
      * Sets the value of the 'H' field.
      * @param value The value of 'H'.
      * @return This builder.
      */
    public org.irrigation.schema.ParcelData.Builder setH(int value) {
      validate(fields()[1], value);
      this.H = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'H' field has been set.
      * @return True if the 'H' field has been set, false otherwise.
      */
    public boolean hasH() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'H' field.
      * @return This builder.
      */
    public org.irrigation.schema.ParcelData.Builder clearH() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ParcelData build() {
      try {
        ParcelData record = new ParcelData();
        record.T = fieldSetFlags()[0] ? this.T : (java.lang.Integer) defaultValue(fields()[0]);
        record.H = fieldSetFlags()[1] ? this.H : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ParcelData>
    WRITER$ = (org.apache.avro.io.DatumWriter<ParcelData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ParcelData>
    READER$ = (org.apache.avro.io.DatumReader<ParcelData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.T);

    out.writeInt(this.H);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.T = in.readInt();

      this.H = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.T = in.readInt();
          break;

        case 1:
          this.H = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










